language: python

python:
- "3.5"

install:
- pip install -r requirements.txt

script:
- coverage run --source=plugins -m unittest discover tests "*_test.py"
- flake8 .

after_success: coveralls

notifications:
  slack: teamtaverna:iP55LweubU8UOBgu9e0cTeED
